version: 2.1

orbs:
  node: circleci/node@4.1

commands:
  setup-node-and-yarn-install-with-cache:
    steps:
      - node/install:
          install-yarn: true
          node-version: << parameters.version >>
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock

jobs:
  lint-and-test:
    executor: node
    parameters:
      version:
        type: string
    steps:
      - checkout
      - setup-node-and-yarn-install-with-cache
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
workflows:
  ci-build:
    jobs:
      - lint-and-test:
          matrix:
            parameters:
              version: ['15.1', 'lts', '12.21']
