version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  lint-and-test:
    executor:
      name: node/default
      tag: << parameters.version >>
    parameters:
      version:
        type: string
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: << parameters.version >>
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
workflows:
  ci-build:
    jobs:
      - lint-and-test:
          matrix:
            parameters:
              version: ['12.22.1', '14.16.0']
