version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test:
    parameters:
      version:
        type: string
    steps:
      - checkout
      - node/install:
          node-version: << parameters.version >>
          install-yarn: true
      - run: yarn test
workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              version: ['15.1', 'lts', '12.21']
