version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test:
    executor: node
    parameters:
      version:
        type: string
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - install: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run: yarn test
workflows:
  all-tests:
    jobs:
      - node/test:
          
          matrix:
            parameters:
              version: ['15.1', 'lts', '12.21']
