version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  test:
    executor: node
    parameters:
      version:
        type: string
    steps:
      - checkout
      - install: yarn install --immutable
      - run: yarn test
workflows:
  all-tests:
    jobs:
      - node/test:
          
          matrix:
            parameters:
              version: ['15.1', 'lts', '12.21']
