version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  lint-and-test:
    executor:
      name: node/default
    parameters:
      version:
        type: string
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: << parameters.version >>
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Tests
          command: yarn test
workflows:
  ci-build:
    jobs:
      - lint-and-test:
          matrix:
            parameters:
              version: ['15.1', 'lts', '12.21']
